.\" qpxtool is released under the GNU GENERAL PUBLIC LICENSE.
.TH "qpxtool" "1" "26 Feb 2014"
.SH "NAME"
qpxtool \- a gui to control qpxtool command line interfaces (cli). 
.SH "SYNOPSIS"
\fBqpxtool 
.br 
.SH "DESCRIPTION"
qpxtool is a gui to control qscan and cdvdcontrol.

\fR \fB
\fR \fB
\fR \fB
\fRplease report man page improvements to T.Maguin@web.de\fB	
