.\" qscand is released under the GNU GENERAL PUBLIC LICENSE.
.TH "qscand" "1" "26 Feb 2014"
.SH "NAME"
qscand \- network wrapper for qscan 
.SH "SYNOPSIS"
\fBqscand [\-h] 
.br 
\fBqscand [\-n] [\-d] 
.br 
\fBqscand \-i NW-INTERFACE-ADDRESS \-p LISTEN-PORT \fR
.br 
.SH "DESCRIPTION"
qscand is a network wrapper which gives you access to your devices through the TCP/IP stacK. 

.SH "OPTIONS"

\fB\-h, \-\-help\fR
.br
		show help
 
\fB\-n, \-\-nodaemon\fR	
.br
		don't daemonize qscand  

\fB\-d, \-\-debug\fR	
.br
		run qscand in debug mode  

\fB\-i, \-\-iface\fR
.br
		select ip address for listening  

\fB\-p, \-\-port\fR	
.br
		select port for listening  

\fR \fB
\fR \fB
\fR \fB
\fRplease report man page improvements to T.Maguin@web.de\fB	
