all: qproject

qproject:
	qmake -project MOC_DIR="moc" OBJECTS_DIR="obj" -o qpxtool.pro \
	QT+=network \
	CONFIG+="thread" \
	INCLUDEPATH+="../lib/include" \
	INCLUDEPATH+="include"

.PHONY: qproject all
