name: autobuild

on:
  push:
    branches:
      - 'master'
      - 'dev'
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  win64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: git make pkg-config mingw-w64-x86_64-gcc mingw-w64-x86_64-qt6-base mingw-w64-x86_64-qt6-tools mingw-w64-x86_64-ntldd unzip zip
      - name: git config
        run: git config --global core.autocrlf input
        shell: bash
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: configure (release)
        id: conf
        run: |
          git describe --dirty --tags --match 'v*'
          version="$(git describe --dirty --tags --match 'v*')"
          sed -i -re "s/^#define VERSION.*/#define VERSION \"${version:1}-speed47\"/" */*/version.h
          echo "version=${version:1}" >> $GITHUB_OUTPUT
          ./configure
      - name: make (release)
        run: nproc && make -j$(nproc)
      - name: check executable (release)
        run: |
          file gui/release/qpxtool.exe
          file gui/release/qpxtool.exe | grep -q 'x86-64'
          file gui/release/qpxtool.exe | grep -q 'for MS Windows'
      - name: install UPX
        run: |
          wget -q https://github.com/upx/upx/releases/download/v5.1.1/upx-5.1.1-win64.zip
          unzip upx-5.1.1-win64.zip
      - name: prepare dist
        id: dist
        run: ./.github/workflows/make-dist.sh ${{ steps.conf.outputs.version }}
      - name: Tag if needed
        id: tag
        if: github.ref_type == 'branch'
        run: |
          case "$GITHUB_REF_NAME" in
            dev)    tagname=devel
                    git tag -f $tagname
                    git push -f origin $tagname
                    echo "draft=true" >> $GITHUB_OUTPUT
                    echo "relname=Dev Build" >> $GITHUB_OUTPUT
                    ;;
            master) tagname=latest
                    git tag -f $tagname
                    git push -f origin $tagname
                    echo "draft=false" >> $GITHUB_OUTPUT
                    echo "relname=Continuous Build" >> $GITHUB_OUTPUT
                    ;;
            v*)     tagname=$GITHUB_REF_NAME
                    echo "draft=true" >> $GITHUB_OUTPUT
                    echo "relname=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
                    ;;
            *)      exit 1;;
          esac
          echo "prerelease=true" >> $GITHUB_OUTPUT
          echo "tagname=$tagname" >> $GITHUB_OUTPUT
      - name: Delete old assets
        if: github.ref_type == 'branch'
        uses: mknejp/delete-release-assets@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "refs/tags/${{ steps.tag.outputs.tagname }}"
          fail-if-no-assets: false
          fail-if-no-release: false
          assets: |
            qpxtool-*.zip
      - name: Upload new assets
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: "${{ steps.tag.outputs.prerelease }}"
          draft: "${{ steps.tag.outputs.draft }}"
          name: "${{ steps.tag.outputs.relname }}"
          tag_name: "${{ steps.tag.outputs.tagname }}"
          files: ${{ steps.dist.outputs.archive }}

  linux64-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: install prerequisites on host
        run: sudo apt-get update && sudo apt-get install -y fuse
      - name: docker
        run: |
          mkdir -p /tmp/dist
          docker run --device /dev/fuse --privileged --name uu -d -v $PWD:/qpxtool -v /tmp/dist:/dist ubuntu:22.04 sleep 1800
      - name: install prerequisites in docker
        run: docker exec uu sh -c 'apt-get update && apt-get install -y fuse qt6-base-dev binutils g++ file qt6-tools-dev-tools qt6-l10n-tools make pkg-config libgl1-mesa-dev libxcb-cursor0'
      - name: configure
        id: conf
        run: |
          git describe --dirty --tags --match 'v*'
          version="$(git describe --dirty --tags --match 'v*')"
          sed -i -re "s/^#define VERSION.*/#define VERSION \"${version:1}-speed47\"/" */*/version.h
          echo "version=${version:1}" >> $GITHUB_OUTPUT
          docker exec uu sh -c 'cd /qpxtool && ./configure --prefix=/usr --libdir=/usr/lib'
      - name: make
        run: docker exec uu sh -c 'make -C /qpxtool -j$(nproc)'
      - name: make install
        run: docker exec uu sh -c "make -C /qpxtool install DESTDIR=/dist"
      - name: build appimage in docker
        run: |
          wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          wget -q https://github.com/AppImage/type2-runtime/releases/download/continuous/runtime-x86_64
          chmod 755 linuxdeploy-x86_64.AppImage linuxdeploy-plugin-qt-x86_64.AppImage runtime-x86_64
          docker exec \
              -e QMAKE=/usr/bin/qmake6 \
              -e LINUXDEPLOY_OUTPUT_VERSION=v"${{ steps.conf.outputs.version }}" \
              -e ARCH=x86_64 \
              -e ME=$UID \
              -e LD_LIBRARY_PATH=/dist/usr/lib \
              -e LDAI_RUNTIME_FILE=runtime-x86_64 \
              -e LDAI_NO_APPSTREAM=1 \
               uu sh -c '
            find /dist
            cd /qpxtool
            ./linuxdeploy-x86_64.AppImage -d /dist/usr/share/applications/qpxtool.desktop -i /dist/usr/share/pixmaps/qpxtool.png --icon-filename qpxtool \
              --custom-apprun=contrib/AppRun --appdir /dist/ --plugin qt --output appimage
            chown $ME QPx*.AppImage
          '
      - name: get appimage name
        id: dist
        run: |
          archive=$(find . -type f -name "QPx*.AppImage")
          echo "archive=$archive" >> $GITHUB_OUTPUT
          echo "appimage is <$archive>"
      - name: Tag if needed
        id: tag
        if: github.ref_type == 'branch'
        run: |
          case "$GITHUB_REF_NAME" in
            dev)    tagname=devel
                    git tag -f $tagname
                    git push -f origin $tagname
                    echo "draft=true" >> $GITHUB_OUTPUT
                    echo "relname=Dev Build" >> $GITHUB_OUTPUT
                    ;;
            master) tagname=latest
                    git tag -f $tagname
                    git push -f origin $tagname
                    echo "draft=false" >> $GITHUB_OUTPUT
                    echo "relname=Continuous Build'" >> $GITHUB_OUTPUT
                    ;;
            v*)     tagname=$GITHUB_REF_NAME
                    echo "draft=false" >> $GITHUB_OUTPUT
                    echo "relname=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
                    ;;
            *)      exit 1;;
          esac
          echo "prerelease=true" >> $GITHUB_OUTPUT
          echo "tagname=$tagname" >> $GITHUB_OUTPUT
      - name: Delete old assets
        if: github.ref_type == 'branch'
        uses: mknejp/delete-release-assets@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "refs/tags/${{ steps.tag.outputs.tagname }}"
          fail-if-no-assets: false
          fail-if-no-release: false
          assets: |
            QPxTool-*.AppImage
      - name: Upload new assets
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: "${{ steps.tag.outputs.prerelease }}"
          draft: "${{ steps.tag.outputs.draft }}"
          name: "${{ steps.tag.outputs.relname }}"
          tag_name: "${{ steps.tag.outputs.tagname }}"
          files: ${{ steps.dist.outputs.archive }}
